image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web

build-main:
  stage: build
  script:
    - docker pull $IMAGE:CI_COMMIT_SHORT_SHA || true
    - docker pull $IMAGE:production || true
    - docker build
      --cache-from $IMAGE:CI_COMMIT_SHORT_SHA
      -t $IMAGE:$CI_COMMIT_SHORT_SHA
      --file ./backend/Dockerfile
      "."
    - docker build
      --cache-from $IMAGE:production
      -t $IMAGE:production
      -t $HEROKU_REGISTRY_IMAGE
      --file ./backend/Dockerfile
      "."
    - docker push $IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE:production
  only:
    - main

deploy-main:
  stage: deploy
  script:
    - apk add --no-cache curl
    - docker pull $IMAGE:CI_COMMIT_SHORT_SHA || true
    - docker pull $IMAGE:production || true
    - docker build
      --cache-from $IMAGE:CI_COMMIT_SHORT_SHA
      -t $IMAGE:$CI_COMMIT_SHORT_SHA
      --file ./backend/Dockerfile
      "."
    - docker build
      --cache-from $IMAGE:production
      -t $IMAGE:production
      -t $HEROKU_REGISTRY_IMAGE
      --file ./backend/Dockerfile
      "."
    - docker push $IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE:production
    - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker push $HEROKU_REGISTRY_IMAGE
    - chmod +x ./release.sh
    - ./release.sh
  only:
    - main
