version: "3.8"

services:

  app:
    container_name: backend_${COMPOSE_PROJECT_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:8000
    volumes:
      - type: bind
        source: ./backend
        target: /opt/app
