services:

  app:
    container_name: backend_${COMPOSE_PROJECT_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:8000
      - 3333:3333
    volumes:
      - ./backend/:/opt/app
      #- ./backend/staticfiles/:/opt/app/staticfiles
    networks:
      - app_network

networks:
  app_network:
    driver: bridge