services:

  app:
    container_name: backend_${COMPOSE_PROJECT_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:8000
      - 3333:3333
    depends_on:
      - db
    volumes:
      - ./backend/:/opt/app
    networks:
      - app_network

  db:
    container_name: db_${COMPOSE_PROJECT_NAME}
    image: postgres:14.1-bullseye
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
    - ./postgres/data:/data/postgres
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
